//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0
pub use super::dictionary_entries::Entity as DictionaryEntries;
pub use super::inventory_items::Entity as InventoryItems;
pub use super::users::Entity as Users;
